services:
  - type: web
    name: traillend-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn traillend_final_web.wsgi:application"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_KEY_JSON
        sync: false
